In [ ]:
import cv2, sys
import numpy as np
import geopandas as gpd
import os
from micasense import metadata
sys.path.append("d:/USDA-NIFA/Code")
os.chdir("d:/USDA-NIFA/Code")
os.getcwd()

'c:\\Users\\vince\\Desktop\\USDA-NIFA\\Code'

In [26]:
def transform2seconds(time_str):
    """Convert a time string in the format 'HH:MM:SS' to total seconds."""
    h, m, s = map(float, time_str.split(':'))
    return h * 3600 + m * 60 + s

In [ ]:
root_folder = "B1"
image_folder = os.path.join(root_folder, "Processed", "capture")
geojason_file = os.path.join(root_folder, "Processed", "imageSet.json")
UTM_CRS = "EPSG:32616" # UTM Zone 16N for Indiana

gdf = gpd.read_file(geojason_file)
gdf['img_path'] = gdf['capture_id'].apply(lambda x: os.path.normpath(os.path.join(image_folder, f"{x}.tif")))
gdf['capture_time'] = gdf['capture_id'].apply(lambda x: transform2seconds(metadata.Metadata(os.path.normpath(os.path.join(image_folder, f"{x}.tif"))).get_item("EXIF:GPSTimeStamp")))

gdf_utm = gdf.to_crs(UTM_CRS)

In [28]:
gdf.to_file('B1/B1.geojson', driver='GeoJSON')

In [31]:
gdf.sort_values('capture_time', inplace=True)

In [32]:
gdf

,altitude,capture_id,dls-yaw,dls-pitch,dls-roll,irr-475,irr-560,irr-668,irr-842,irr-717,geometry,img_path,capture_time
0,264.483,C66J2yEVbQEqd1DqOfxX,0.399576,-0.204540,-0.021003,1.004336,0.908405,0.809841,0.481614,0.608052,POINT (-87.36954 40.52615),B1\Processed\capture\C66J2yEVbQEqd1DqOfxX.tif,51962.315365
1,264.474,t70ahUr16cp6UH4Tin8O,0.288751,-0.221410,-0.015860,0.973489,0.884066,0.790512,0.470700,0.592624,POINT (-87.36934 40.52614),B1\Processed\capture\t70ahUr16cp6UH4Tin8O.tif,51965.315562
2,264.449,XFvoJyixESrVBi3ceTip,0.230614,-0.211274,-0.014035,0.945985,0.861420,0.771559,0.459813,0.577820,POINT (-87.36915 40.52613),B1\Processed\capture\XFvoJyixESrVBi3ceTip.tif,51967.307759
3,264.424,TgLnxGi4xuMMb7gQ40vH,0.189570,-0.200687,-0.014505,0.918871,0.838744,0.752193,0.448628,0.562823,POINT (-87.36893 40.52612),B1\Processed\capture\TgLnxGi4xuMMb7gQ40vH.tif,51969.255124
4,264.415,TAaIqlfaTJndBYyPdBK0,0.149158,-0.149450,-0.033822,0.890362,0.814161,0.730496,0.435999,0.546281,POINT (-87.36869 40.52611),B1\Processed\capture\TAaIqlfaTJndBYyPdBK0.tif,51971.190963
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,267.713,WrJyJUiRqKdmi1pz2gHw,-0.113793,-0.178372,-0.046018,0.836168,0.773579,0.692940,0.416478,0.517223,POINT (-87.36243 40.52675),B1\Processed\capture\WrJyJUiRqKdmi1pz2gHw.tif,52583.253484
296,267.702,4nnZzqNLAdMqK5XbA3rt,-0.110040,-0.188049,-0.050912,0.836056,0.773491,0.692841,0.416421,0.517143,POINT (-87.3622 40.52674),B1\Processed\capture\4nnZzqNLAdMqK5XbA3rt.tif,52585.180345
297,267.700,alltmkEK2XR53NQ97L41,-0.101572,-0.212178,-0.065845,0.836352,0.773774,0.693101,0.416589,0.517352,POINT (-87.36196 40.52673),B1\Processed\capture\alltmkEK2XR53NQ97L41.tif,52587.308150
298,267.685,uPiyAB3YxiZl2H1yjBhB,-0.102260,-0.205380,-0.055368,0.836092,0.773424,0.692733,0.416348,0.517103,POINT (-87.36173 40.52671),B1\Processed\capture\uPiyAB3YxiZl2H1yjBhB.tif,52589.221424
299,267.656,B2btlHCEnBEf5PMBopjb,-0.097309,-0.217954,-0.041036,0.836554,0.773861,0.693190,0.416626,0.517440,POINT (-87.36149 40.5267),B1\Processed\capture\B2btlHCEnBEf5PMBopjb.tif,52591.188760

In [18]:
gdf

,altitude,capture_id,dls-yaw,dls-pitch,dls-roll,irr-475,irr-560,irr-668,irr-842,irr-717,geometry,img_path
0,264.483,C66J2yEVbQEqd1DqOfxX,0.399576,-0.204540,-0.021003,1.004336,0.908405,0.809841,0.481614,0.608052,POINT (-87.36954 40.52615),B1\Processed\capture\C66J2yEVbQEqd1DqOfxX.tif
1,264.474,t70ahUr16cp6UH4Tin8O,0.288751,-0.221410,-0.015860,0.973489,0.884066,0.790512,0.470700,0.592624,POINT (-87.36934 40.52614),B1\Processed\capture\t70ahUr16cp6UH4Tin8O.tif
2,264.449,XFvoJyixESrVBi3ceTip,0.230614,-0.211274,-0.014035,0.945985,0.861420,0.771559,0.459813,0.577820,POINT (-87.36915 40.52613),B1\Processed\capture\XFvoJyixESrVBi3ceTip.tif
3,264.424,TgLnxGi4xuMMb7gQ40vH,0.189570,-0.200687,-0.014505,0.918871,0.838744,0.752193,0.448628,0.562823,POINT (-87.36893 40.52612),B1\Processed\capture\TgLnxGi4xuMMb7gQ40vH.tif
4,264.415,TAaIqlfaTJndBYyPdBK0,0.149158,-0.149450,-0.033822,0.890362,0.814161,0.730496,0.435999,0.546281,POINT (-87.36869 40.52611),B1\Processed\capture\TAaIqlfaTJndBYyPdBK0.tif
...,...,...,...,...,...,...,...,...,...,...,...,...
295,267.713,WrJyJUiRqKdmi1pz2gHw,-0.113793,-0.178372,-0.046018,0.836168,0.773579,0.692940,0.416478,0.517223,POINT (-87.36243 40.52675),B1\Processed\capture\WrJyJUiRqKdmi1pz2gHw.tif
296,267.702,4nnZzqNLAdMqK5XbA3rt,-0.110040,-0.188049,-0.050912,0.836056,0.773491,0.692841,0.416421,0.517143,POINT (-87.3622 40.52674),B1\Processed\capture\4nnZzqNLAdMqK5XbA3rt.tif
297,267.700,alltmkEK2XR53NQ97L41,-0.101572,-0.212178,-0.065845,0.836352,0.773774,0.693101,0.416589,0.517352,POINT (-87.36196 40.52673),B1\Processed\capture\alltmkEK2XR53NQ97L41.tif
298,267.685,uPiyAB3YxiZl2H1yjBhB,-0.102260,-0.205380,-0.055368,0.836092,0.773424,0.692733,0.416348,0.517103,POINT (-87.36173 40.52671),B1\Processed\capture\uPiyAB3YxiZl2H1yjBhB.tif
299,267.656,B2btlHCEnBEf5PMBopjb,-0.097309,-0.217954,-0.041036,0.836554,0.773861,0.693190,0.416626,0.517440,POINT (-87.36149 40.5267),B1\Processed\capture\B2btlHCEnBEf5PMBopjb.tif

In [19]:
m = gdf.explore(
    column='altitude', 
    cmap='viridis',
    tooltip=['capture_id', 'altitude'], # Show these when hovering
    popup=True,                         # Show all attributes when clicking
    marker_kwds={'radius': 5},          # Size of the points
    style_kwds={'stroke': True, 'color': 'white', 'weight': 1}
)

In [11]:
m.save("uav_flight_map.html")

[0]